### PR TITLE
Make MDXJSEsm value optional

### PR DESCRIPTION
**Pull request by remcohaszing**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

It may be created with without a value.

A practical example can be found [in remark-mdx-frontmatter](https://github.com/remcohaszing/remark-mdx-frontmatter/blob/v1.0.1/src/index.ts#L49-L84).

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
LGTM, thanks @remcohaszing!

**Comment by wooorm** [comment]
On the question whether `mdast-util-mdxjs-esm` should handle a node w/o `value` on the serialization side, I’d say yes.
Generally the code in unified tries to deal well with non-conforming ASTs. So similarly a `text` node w/o values is also serialized as `''` rather than `'underined'`.

But the goal of TypeScript is to prevent malformed ASTs. Literals should have a value. They are parsed with a value always.
Sure that might not make the most sense for your use case, but why should the types be changes to allow a missing `value`, rather a small fix in your utility that sets `value: ''`?

**Comment by remcohaszing** [comment]
The value represents the code, which doesn’t exist in this case. I think the absense of the property better reflects this than an empty string.

Setting `value: ''` works for me as well though. I just think making the property optional is slightly cleaner. It’s your call. :)

**Comment by remcohaszing** [comment]
> The most proper way would be to use astring and generate serialized JS as value. This is probably more work than it’s worth. On the other hand, astring is probably already included somewhere in this pipeline. This would make codemods of a .md -> .mdx file possible, where originally YAML was used but it’s now turned into an export. And it would allow people to run for example a hypothetical remark-mdx-prettier plugin to prettify their code.

I agree this is the most proper solution. However, it’s currently not needed and I fear this impacts performance for no gain. I’d love to be wrong about this though.

**Comment by wooorm** [comment]
Agreed on that too, it’s not needed yet. We’ll cross that bridge when we get there.
I do think performance would be mostly fine, astring should be fast enough and I’m assuming serialization is faster than parsing things.

@ChristianMurphy Are you still in favor of this? I’m leaning towards reasonably against.

**Comment by ChristianMurphy** [comment]
With the context that `value` is intended to be there, I'd lean against it as well.
It does raise a related thought though, since JS libraries can potentially feed invalid ASTs that TS libraries may not expect, would it make sense to extend https://github.com/syntax-tree/mdast-util-assert (or create a new version of it) that can check MDX ASTs are valid at runtime?

**Pull request closed without merging**
